name: Build .exe

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Specify your .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Publish .exe
        run: dotnet publish --configuration Release -r win-x64 --self-contained --output ./output

      - name: Upload .exe to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: ./output  # Path where your .exe is located
